
name: Compile JCINK Theme using Cybertron

on:
  push:
    branches: ["main"]
    
  workflow_dispatch:
    # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cybertron
        uses: sigoden/install-binary@v1
        with:
          repo: magratheaguide/cybertron
          name: cybertron
          # tag: v1.1.0
      
      - name: Build theme XML
        run: cybertron build --name "${{ vars.theme_name }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: "${{ vars.theme_name }}.xml"