
name: Compile JCINK Theme using Cybertron

on:
  push:
    branches: ["main"]

  workflow_dispatch:
    # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Upload generated site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site

  flatten:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download generated site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: _site
      - name: Flatten assets
        run: ./_tools/flat_assets.sh _site "${{ vars.asset_url_prefix }}" $(git describe --always --dirty --broken)
      - name: Upload flattened assets
        uses: actions/upload-artifact@v4
        with:
          name: flat_assets
          path: _site/files/
      - name: Upload flattened site
        uses: actions/upload-artifact@v4
        with:
          name: flat_site
          path: _site/
        
  pack:
    runs-on: ubuntu-latest
    needs: flatten
    strategy:
      matrix:
        theme_variant: [default, dark, light]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download generated site
        uses: actions/download-artifact@v4
        with:
          name: flat_site
          path: _site
      - name: Install Cybertron
        uses: sigoden/install-binary@v1
        with:
          repo: magratheaguide/cybertron
          name: cybertron
          # tag: v1.1.0
      - name: Build skin xml
        run: cybertron build
          --name "${{ vars.theme_name }} ${{ matrix.theme_variant }} $(git describe --always --dirty --broken)"
          --macros-folder "_site/macros"
          --stylesheet "_site/assets/css/just-the-docs-${{ matrix.theme_variant }}.css"
          --templates-folder "_site/html-templates"
          --wrapper "_site/wrapper.html"
          --output-directory "_site/"
      - name: Normalize skin filename
        run: mv "_site/${{ vars.theme_name }} ${{ matrix.theme_variant }} $(git describe --always --dirty --broken).xml" "_site/${{ vars.theme_name }}-${{ matrix.theme_variant }}.xml"
      - name: Upload skin xml
        uses: actions/upload-artifact@v4
        with:
          name: skin-${{ matrix.theme_variant }}
          path: "_site/${{ vars.theme_name }}-${{ matrix.theme_variant }}.xml"

  release:
    runs-on: ubuntu-latest
    needs:
      - flatten
      - pack
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Collect default theme
        uses: actions/download-artifact@v4
        with:
          name: skin-default
          path: pack/
      - name: Collect dark theme
        uses: actions/download-artifact@v4
        with:
          name: skin-dark
          path: pack/
      - name: Collect light theme
        uses: actions/download-artifact@v4
        with:
          name: skin-light
          path: pack/
      - name: Collect flattened assets
        uses: actions/download-artifact@v4
        with:
          name: flat_assets
          path: pack/
      - name: Upload skinpack
        uses: actions/upload-artifact@v4
        with:
          name: skinpack
          path: pack/
    
  deploy:
    runs-on: ubuntu-latest
    needs: pack
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: '**/requirements.txt'
      - name: Install selenium
        run: pip install -r _tools/jcink_upload/requirements.txt
      - name: Collect skinpack
        uses: actions/download-artifact@v4
        with:
          name: skinpack
          path: pack
      - name: Install skinpack
        run: python _tools/jcink_upload/main.py
          --assets pack/assets_*
          --assets-root pack/
          --skin pack/*default*.xml
          --skin pack/*dark*.xml
          --skin pack/*light*.xml
        env:
          JCINK_ADMINURL: ${{ secrets.JCINK_ADMINURL }}
          JCINK_USERNAME: ${{ secrets.JCINK_USERNAME }}
          JCINK_PASSWORD: ${{ secrets.JCINK_PASSWORD }}

