
name: Compile JCINK Theme using Cybertron

on:
  push:
    branches: ["main"]

  workflow_dispatch:
    # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl REPLACE_ME
        env:
          JEKYLL_ENV: production
      - name: Upload generated site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site

  flatten:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: site
          path: _site
      - name: Build flat assets
        run: ./flat_assets.sh REPLACE_ME _site _site/flat_assets "${{ vars.asset_url_prefix }}"
      - name: Upload flat assets
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: _site/flat_assets
      - name: Upload flattened site
        uses: actions/upload-artifact@v4
        with:
          name: flat_site
          path: _site
        
  pack:
    runs-on: ubuntu-latest
    needs: flatten
    strategy:
      matrix:
        theme_variant: [default, dark, light]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: site
          path: _site
      - name: Install Cybertron
        uses: sigoden/install-binary@v1
        with:
          repo: magratheaguide/cybertron
          name: cybertron
          # tag: v1.1.0
      - name: Build theme XML
        run: cybertron build
          --name "${{ vars.theme_name }}-${{ matrix.theme_variant }}"
          --macros-folder "_site/macros"
          --stylesheet "_site/assets/css/just-the-docs-${{ matrix.theme_variant }}.css"
          --templates-folder "_site/templates"
          --wrapper "_site/wrapper.html"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.theme_variant }}-theme
          path: "${{ vars.theme_name }}-${{ matrix.theme_variant }}.xml"
