
name: Compile JCINK Theme using Cybertron

on:
  push:
    branches: ["main"]

  workflow_dispatch:
    # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl REPLACE_ME
        env:
          JEKYLL_ENV: production
      
      - name: Build flat assets
        run: ./flat_assets.sh REPLACE_ME _site _site/flat_assets "${{ vars.asset_url_prefix }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: _site/flat_assets

  pack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        theme_variant: [default, dark, light]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cybertron
        uses: sigoden/install-binary@v1
        with:
          repo: magratheaguide/cybertron
          name: cybertron
          # tag: v1.1.0
      - name: Build theme XML
        run: >-
          cybertron build
            --name "${{ vars.theme_name }}-${{ matrix.theme_variant }}"
            --macros_folder "_site/macros"
            --stylesheet "_site/assets/css/just-the-docs-${{ matrix.theme_variant }}.css"
            --templates-folder "_site/templates"
            --wrapper "_site/wrapper.html"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: "${{ vars.theme_name }}-${{ matrix.theme_variant }}.xml"
